auctions/urls.py
from django.urls import path
from .views import AuctionDetailView, AuctionListView

app_name = 'auctions'

urlpatterns = [
    path('', AuctionListView.as_view(), name='auction-list'),
    path('<pk>/', AuctionDetailView.as_view(), name='auction-detail')
    
]

base/urls.py
from django.urls import path, include
from .views.portfolio import PortfolioPage
from .views.home import HomeView
from .views.cardview import CardDetailView
from .views.register import RegisterPage
from .views.login import LoginPage
from django.contrib.auth.views import LogoutView

app_name = 'base'

urlpatterns = [    
    path('login/', LoginPage, name='login'),
    path('playercard/<str:slug>/', CardDetailView.as_view(), name='playercard'),
    path('register/', RegisterPage, name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('portfolio/', PortfolioPage, name='portfolio'),
    path('', HomeView, name='home'),
    
]

djolowin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('allauth.urls')),
    path('auctions/', include('auctions.urls')),
    path('market/', include('trades.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trades/urls.py
from django.urls import path, include
from .views import bundle_list

app_name = 'trades'

urlpatterns = [
    path('', bundle_list, name = 'bundle-list'),
]

templates/footer.html
<footer class="bg-dark text-center text-white">
			<!-- Grid container -->
			<div class="container p-3">
				<!-- Section: Social media -->
				<section class="mb-4">
					<!-- Facebook -->
					<a class="facebook-btn" href="#!" role="button"
						><i class="fa fa-facebook-f"></i
					></a>

					<!-- Twitter -->
					<a class="twitter-btn" href="#!" role="button"
						><i class="fa fa-twitter"></i
					></a>

					<!-- Google -->
					<a class="google-btn" href="#!" role="button"
						><i class="fa fa-google"></i
					></a>

					<!-- Instagram -->
					<a class="instagram-btn" href="#!" role="button"
						><i class="fa fa-instagram"></i
					></a>

					<!-- Linkedin -->
					<a class="linkedin-btn" href="#!" role="button"
						><i class="fa fa-linkedin"></i
					></a>

					<!-- Github -->
					<a class="github-btn" href="#!" role="button"
						><i class="fa fa-github"></i
					></a>
				</section>
				<!-- Section: Form -->
				<section class="">
				<form action="">
					<!--Grid row-->
					<div class="row d-flex justify-content-center">
					<!--Grid column-->
					<div class="col-auto">
						<p class="pt-2">
						<strong>Sign up for our newsletter</strong>
						</p>
					</div>
					<!--Grid column-->

					<!--Grid column-->
					<div class="col-md-5 col-12">
						<!-- Email input -->
						<div class="form-outline form-white mb-4">
						<input type="email" id="form5Example21" class="form-control" />
						<label class="form-label" for="form5Example21">Email address</label>
						</div>
					</div>
					<!--Grid column-->

					<!--Grid column-->
					<div class="col-auto">
						<!-- Submit button -->
						<button type="submit" class="btn btn-outline-light mb-4">
						Subscribe
						</button>
					</div>
					<!--Grid column-->
					</div>
					<!--Grid row-->
				</form>
				</section>

				<!-- Section: Links -->
				<section class="">
					<!--Grid row-->
					<div class="row">
						<!--Grid column-->
						<div class="col-lg-4 col-md-6 mb-3 mb-md-0">
							<ul class="list-unstyled mb-0">
								<li><a href="#!" class="text-white">Game Rules</a><br /></li>
								<li>
									<a href="#!" class="text-white">Terms & Conditions</a><br />
								</li>
							</ul>
						</div>
						<!--Grid column-->

						<!--Grid column-->
						<div class="col-lg-4 col-md-6 mb-3 mb-md-0">
							<ul class="list-unstyled mb-0">
								<li>
									<a href="#!" class="text-white">Privacy Policy</a><br />
								</li>
								<li><a href="#!" class="text-white">Help</a><br /></li>
							</ul>
						</div>
						<!--Grid column-->

						<!--Grid column-->
						<div class="col-lg-4 col-md-6 mb-3 mb-md-0">
							<ul class="list-unstyled mb-0">
								<li><a href="#!" class="text-white">Contact Us</a><br /></li>
								<li><a href="#!" class="text-white">Invite Friends</a><br /></li>
							</ul>
						</div>
						<!--Grid column-->
						<!--Grid column-->
					</div>
					<!--Grid row-->
				</section>
				<!-- Section: Links -->
				<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
					<p>
						© 2022 Copyright:
						<a class="text-white	" href="/"> DjoloWin.com</a>
					</p>
				</div>
			</div>
			<!-- Grid container -->
			<!-- Copyright -->
			<!-- Copyright -->
		</footer>

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'css/main.css/' %}" />
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
		/>
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
			rel="stylesheet"
		/> 
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
		<link href="{% static 'css/mdb.min.css' %}" rel="stylesheet" />
		<link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
			integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
			crossorigin="anonymous"
		></script>
		{% block scripts %} {% endblock scripts %}
		<title>DjoloWin</title>
		<style type="text/css">
			.wrapper {
				max-width: 1164px;
				margin: auto;
			}
		</style>
	</head>

	<body>
		<div class="wrapper">
			{% include "navbar.html" %}
			<header>
				<div class="mt-5 pt-4">
					{% if messages %} {% for message in messages %}
					<div
						class="alert alert-{{ message.tags }} alert-dismissible fade show"
						role="alert"
					>
						{{ message }}
						<button
							type="button"
							class="close"
							data-dismiss="alert"
							aria-label="Close"
						>
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					{% endfor %} {% endif %}
				</div>
			</header>
			<main>
				{% block content %} {% endblock content %} {% block extra_body %}
				{% endblock extra_body %}
			</main>
			<!-- Footer -->
			{% include "footer.html" %} {% include "scripts.html" %}
			{% block extra_scripts %} {% endblock extra_scripts %}
			<!-- Footer -->
			<script src="{% static 'js/main.js/' %}"></script>
		</div>
	</body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="/"
		><img
			class="d-inline-block align-text-center"
			src="{% static 'img/elephants.jpg' %}"
			alt="Elephant Logo"
			width="40"
			height="40"
		/>DjoloWin</a
	>
	<button
		class="navbar-toggler"
		type="button"
		data-bs-toggle="collapse"
		data-bs-target="#navbarSupportedContent"
		aria-controls="navbarSupportedContent"
		aria-expanded="false"
		aria-label="Toggle navigation"
	>
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			<li class="nav-item dropdown">
				<a
					class="nav-link dropdown-toggle"
					href="#"
					role="button"
					data-bs-toggle="dropdown"
					aria-expanded="false"
				>
					<i class="fa fa-user"></i>My Profile</a
				>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="#">My Squad</a>
					<div class="dropdown-divider"></div>
					<a class="dropdown-item" href="{% url 'base:portfolio' %}">My Portfolio</a>
					<a class="dropdown-item" href="#">My Wallet</a>
				</div>
			</li>
			<li class="nav-item dropdown">
				<a
					class="nav-link dropdown-toggle"
					href="#"
					role="button"
					data-bs-toggle="dropdown"
					aria-expanded="false"
				>
					Marketplace
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{% url 'auctions:auction-list' %}">Auctions</a>
					<a class="dropdown-item" href="{% url 'trades:bundle-list' %}">Bundles</a>
					<a class="dropdown-item" href="#">Special Offers</a>
				</div>
			</li>
			<li class="nav-item dropdown">
				<a
					class="nav-link dropdown-toggle"
					href="#"
					role="button"
					data-bs-toggle="dropdown"
					aria-expanded="false"
				>
					Settings
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="#">Preferences</a>
					<a class="dropdown-item" href="#">Public Profile</a>
					<a class="dropdown-item" href="#">Account Settings</a>
					<a class="dropdown-item" href="#">Security</a>
					<a class="dropdown-item" href="#">Payment Methods</a>
				</div>
			</li>
			<li>
				<a href="#" class="nav-link"
					><i class="fa fa-fw fa-bell"></i>Notification Center</a
				>
			</li>
			<li>
				<a href="{% url 'base:logout' %}" class="nav-link"
					><i class="fa fa-fw fa-power-off"></i>Log Out</a
				>
			</li>
			<li>
				<a href="{% url 'base:login' %}" class="nav-link"
					><i class="fa fa-fw fa-power-in"></i>Log In</a
				>
			</li>
		</ul>
		<form class="d-flex" role="search">
			<input
				class="form-control me-2"
				type="search"
				placeholder="Search"
				aria-label="Search"
			/>
			<button class="btn btn-outline-success" type="submit">Search</button>
		</form>
	</div>
</nav>

templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
    new WOW().init();

</script>